project_id = "aifhrsjamqlnnadukity"

[functions.send-verification-sms]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false