// MOCK DATA - Remove when integrating real POS API
// This file contains all mock data for the booking portal
// Use this as a reference for the expected data structure from your POS system

import { Location, Service, Staff } from '@/types/booking';

// Mock Locations
export const mockLocations: Location[] = [
  {
    id: 'loc-downtown',
    name: 'Mango Nails - Downtown',
    address: '123 Main Street',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90012',
    phone: '(213) 555-0100',
    email: 'downtown@mangonails.com',
    hero_image_url: '/assets/location-downtown.jpg',
    hours_weekday: 'Mon-Sat: 9:00 AM - 7:00 PM',
    hours_weekend: 'Sun: 10:00 AM - 6:00 PM',
    has_deposit_policy: true,
    deposit_percentage: 20,
    cancellation_policy: 'Cancel 24+ hours before for full refund. Cancellations within 24 hours forfeit deposit.',
  },
  {
    id: 'loc-beverly',
    name: 'Mango Nails - Beverly Hills',
    address: '456 Rodeo Drive',
    city: 'Beverly Hills',
    state: 'CA',
    zip_code: '90210',
    phone: '(310) 555-0200',
    email: 'beverly@mangonails.com',
    hero_image_url: '/assets/location-beverly.jpg',
    hours_weekday: 'Mon-Sat: 9:00 AM - 8:00 PM',
    hours_weekend: 'Sun: 10:00 AM - 7:00 PM',
    has_deposit_policy: true,
    deposit_percentage: 25,
    cancellation_policy: 'Cancel 48+ hours before for full refund. Cancellations within 48 hours forfeit deposit.',
  },
];

// Mock Services
export const mockServices: Service[] = [
  // Manicures
  {
    id: 'svc-classic-mani',
    location_id: 'loc-downtown',
    name: 'Classic Manicure',
    category: 'manicure',
    description: 'Traditional nail care with shaping, cuticle work, and polish application.',
    duration_minutes: 30,
    price_cash: 25,
    price_card: 27,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'svc-gel-mani',
    location_id: 'loc-downtown',
    name: 'Gel Manicure',
    category: 'manicure',
    description: 'Long-lasting gel polish application with 2+ weeks of wear.',
    duration_minutes: 45,
    price_cash: 40,
    price_card: 43,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'svc-deluxe-mani',
    location_id: 'loc-downtown',
    name: 'Deluxe Manicure',
    category: 'manicure',
    description: 'Premium manicure with exfoliation, massage, and hydrating treatment.',
    duration_minutes: 60,
    price_cash: 50,
    price_card: 54,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 3,
    is_active: true,
  },
  
  // Pedicures
  {
    id: 'svc-classic-pedi',
    location_id: 'loc-downtown',
    name: 'Classic Pedicure',
    category: 'pedicure',
    description: 'Complete foot care with soak, scrub, cuticle work, and polish.',
    duration_minutes: 45,
    price_cash: 35,
    price_card: 38,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'svc-gel-pedi',
    location_id: 'loc-downtown',
    name: 'Gel Pedicure',
    category: 'pedicure',
    description: 'Classic pedicure with long-lasting gel polish application.',
    duration_minutes: 60,
    price_cash: 50,
    price_card: 54,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'svc-spa-pedi',
    location_id: 'loc-downtown',
    name: 'Spa Pedicure',
    category: 'pedicure',
    description: 'Luxury pedicure with extended massage, paraffin wax, and aromatherapy.',
    duration_minutes: 75,
    price_cash: 65,
    price_card: 70,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 3,
    is_active: true,
  },

  // Extensions
  {
    id: 'svc-acrylic-full',
    location_id: 'loc-downtown',
    name: 'Acrylic Full Set',
    category: 'extensions',
    description: 'Complete acrylic nail extension application with shaping and design.',
    duration_minutes: 90,
    price_cash: 55,
    price_card: 59,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'svc-acrylic-fill',
    location_id: 'loc-downtown',
    name: 'Acrylic Fill',
    category: 'extensions',
    description: 'Maintenance fill for existing acrylic nails.',
    duration_minutes: 60,
    price_cash: 40,
    price_card: 43,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'svc-gel-x-full',
    location_id: 'loc-downtown',
    name: 'Gel-X Full Set',
    category: 'extensions',
    description: 'Premium soft gel extension system for natural-looking length.',
    duration_minutes: 90,
    price_cash: 70,
    price_card: 75,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 3,
    is_active: true,
  },

  // Nail Art
  {
    id: 'svc-nail-art-basic',
    location_id: 'loc-downtown',
    name: 'Basic Nail Art',
    category: 'nail_art',
    description: 'Simple designs per nail - dots, stripes, or basic patterns.',
    duration_minutes: 15,
    price_cash: 5,
    price_card: 7,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'svc-nail-art-detailed',
    location_id: 'loc-downtown',
    name: 'Detailed Nail Art',
    category: 'nail_art',
    description: 'Complex custom designs with multiple colors and techniques.',
    duration_minutes: 30,
    price_cash: 15,
    price_card: 18,
    is_add_on: false,
    discount_when_bundled: 0,
    display_order: 2,
    is_active: true,
  },

  // Add-ons
  {
    id: 'svc-addon-paraffin',
    location_id: 'loc-downtown',
    name: 'Paraffin Wax Treatment',
    category: 'add_ons',
    description: 'Warm paraffin wax dip for deep hydration and smooth skin.',
    duration_minutes: 15,
    price_cash: 10,
    price_card: 12,
    is_add_on: true,
    parent_service_id: 'svc-classic-mani',
    discount_when_bundled: 2,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'svc-addon-callus',
    location_id: 'loc-downtown',
    name: 'Callus Removal',
    category: 'add_ons',
    description: 'Professional removal of rough, hardened skin on feet.',
    duration_minutes: 20,
    price_cash: 15,
    price_card: 17,
    is_add_on: true,
    parent_service_id: 'svc-classic-pedi',
    discount_when_bundled: 3,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'svc-addon-polish-change',
    location_id: 'loc-downtown',
    name: 'Polish Change',
    category: 'add_ons',
    description: 'Quick polish removal and color change without full service.',
    duration_minutes: 15,
    price_cash: 10,
    price_card: 12,
    is_add_on: true,
    discount_when_bundled: 0,
    display_order: 3,
    is_active: true,
  },
];

// Mock Staff
export const mockStaff: Staff[] = [
  {
    id: 'staff-jessica',
    location_id: 'loc-downtown',
    first_name: 'Jessica',
    last_name: 'Chen',
    avatar_emoji: '💅',
    photo_url: undefined,
    bio: 'Specialist in gel manicures and intricate nail art with 8 years experience.',
    status: 'available_now',
    next_available_time: undefined,
    specialties: ['Gel Manicure', 'Nail Art', 'Extensions'],
    is_active: true,
    display_order: 1,
  },
  {
    id: 'staff-maria',
    location_id: 'loc-downtown',
    first_name: 'Maria',
    last_name: 'Rodriguez',
    avatar_emoji: '✨',
    photo_url: undefined,
    bio: 'Expert in spa pedicures and relaxation treatments. Your feet will thank you!',
    status: 'available_now',
    next_available_time: undefined,
    specialties: ['Spa Pedicure', 'Paraffin Treatment', 'Massage'],
    is_active: true,
    display_order: 2,
  },
  {
    id: 'staff-lily',
    location_id: 'loc-downtown',
    first_name: 'Lily',
    last_name: 'Nguyen',
    avatar_emoji: '🌸',
    photo_url: undefined,
    bio: 'Acrylic and Gel-X extension specialist. Creating beautiful, durable nails since 2015.',
    status: 'available_later',
    next_available_time: '2025-10-16T14:00:00Z',
    specialties: ['Acrylic', 'Gel-X', 'Extensions'],
    is_active: true,
    display_order: 3,
  },
  {
    id: 'staff-sophie',
    location_id: 'loc-beverly',
    first_name: 'Sophie',
    last_name: 'Kim',
    avatar_emoji: '👑',
    photo_url: undefined,
    bio: 'Luxury nail artist specializing in custom designs and premium treatments.',
    status: 'available_now',
    next_available_time: undefined,
    specialties: ['Custom Designs', 'Gel-X', 'Nail Art'],
    is_active: true,
    display_order: 1,
  },
];

// Mock available time slots (varies by date)
export const mockTimeSlots: Record<string, string[]> = {
  // Default slots for any date - in 12-hour format with AM/PM
  default: [
    '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
    '12:00 PM', '12:30 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
    '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
    '6:00 PM', '6:30 PM', '7:00 PM'
  ],
};

// Mock unavailable dates (some dates with no availability)
export const mockUnavailableDates: string[] = [
  // Format: YYYY-MM-DD
  // Add some dates that should show as unavailable
  '2025-10-18', // Saturday - fully booked
  '2025-10-22', // Wednesday - staff training day
  '2025-10-25', // Saturday - fully booked
  '2025-11-01', // Saturday - fully booked
];
